LightJason - AgentSpeak(L++): org.lightjason.agentspeak.IBaseTest Class Reference
org.lightjason.agentspeak.IBaseTest Class Reference abstract
base test class with helpers
Protected Member Functions
final void invoketest ()
invoke all test manually
Static Protected Attributes
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Private Member Functions
Set< Method > before ()
reads the before annotated methods
void execute (final Method p_method, final Set< Method > p_before, final Object... p_arguments)
invokes the method within the current object context
void invoke (final Method p_method, final Set< Method > p_before)
invoke method and read if possible the data-provider
Detailed Description
Definition at line 45 of file IBaseTest.java.
Member Function Documentation
before()
Set<Method> org.lightjason.agentspeak.IBaseTest.before () private
Returns
optional before method
Definition at line 154 of file IBaseTest.java.
Referenced by org.lightjason.agentspeak.IBaseTest.invoketest().
execute()
void org.lightjason.agentspeak.IBaseTest.execute (final Method p_method, final Set< Method > p_before, final Object... p_arguments) private
Parameters
p_method method
p_before before method
p_arguments optional arguments
Definition at line 108 of file IBaseTest.java.
Referenced by org.lightjason.agentspeak.action.builtin.TestCActionGraph.addvertexsingle(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.addwithkeystrean(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.clearwithkeystream(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.createerror(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.existswithkeystream(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.exponentialselectionlazy(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.exponentialselectionstrict(), org.lightjason.agentspeak.IBaseTest.invoke(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.is(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isnull(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isnumeric(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.isstring(), org.lightjason.agentspeak.action.builtin.TestCActionRest.jsonlisterror(), org.lightjason.agentspeak.action.builtin.TestCActionRest.jsonobjecterror(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.linearselection(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.parseliteralerror(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.rangeerror(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplan(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.removeplanerror(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.removewithkeystream(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.sublisterror(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.tofloaterror(), org.lightjason.agentspeak.action.builtin.TestCActionRest.xmlobjecterror(), and org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.ziperror().
invoke()
void org.lightjason.agentspeak.IBaseTest.invoke (final Method p_method, final Set< Method > p_before) private
Parameters
p_method method
p_before before method
Definition at line 72 of file IBaseTest.java.
References org.lightjason.agentspeak.IBaseTest.execute().
Referenced by org.lightjason.agentspeak.IBaseTest.invoketest().
invoketest()
final void org.lightjason.agentspeak.IBaseTest.invoketest () protected
Definition at line 56 of file IBaseTest.java.
References org.lightjason.agentspeak.IBaseTest.before(), and org.lightjason.agentspeak.IBaseTest.invoke().
Referenced by org.lightjason.agentspeak.common.TestCPath.main(), org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.main(), org.lightjason.agentspeak.beliefbase.TestCView.main(), org.lightjason.agentspeak.action.builtin.TestCActionBinding.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathShape.main(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionTuple.main(), org.lightjason.agentspeak.agent.TestCUnifier.main(), org.lightjason.agentspeak.action.builtin.TestCActionGeneric.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathInterpolate.main(), org.lightjason.agentspeak.agent.TestCAgent.main(), org.lightjason.agentspeak.agent.TestCAgentExecution.main(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionSet.main(), org.lightjason.agentspeak.beliefbase.TestCViewMap.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlas.main(), org.lightjason.agentspeak.action.builtin.TestCActionCollection.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathLinearprogram.main(), org.lightjason.agentspeak.agent.TestCHanoiTowers.main(), org.lightjason.agentspeak.consistency.TestCMetric.main(), org.lightjason.agentspeak.action.builtin.TestCActionRest.main(), org.lightjason.agentspeak.action.builtin.TestCActionBool.main(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMultimap.main(), org.lightjason.agentspeak.action.builtin.TestCActionCrypto.main(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionMap.main(), org.lightjason.agentspeak.TestCLanguageLabels.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitVector.main(), org.lightjason.agentspeak.action.builtin.TestCActionGenericType.main(), org.lightjason.agentspeak.action.builtin.TestCActionAgent.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasVector.main(), org.lightjason.agentspeak.language.TestCTermVariablesConstant.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathBitMatrix.main(), org.lightjason.agentspeak.action.builtin.TestCActionDateTime.main(), org.lightjason.agentspeak.action.builtin.TestCActionStorage.main(), org.lightjason.agentspeak.action.builtin.TestCActionString.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathStatistics.main(), org.lightjason.agentspeak.action.builtin.TestCActionCollectionList.main(), org.lightjason.agentspeak.action.builtin.TestCActionMath.main(), org.lightjason.agentspeak.action.builtin.TestCActionMathBlasMatrix.main(), and org.lightjason.agentspeak.action.builtin.TestCActionGraph.main().
Member Data Documentation
PRINTENABLE
final boolean org.lightjason.agentspeak.IBaseTest.PRINTENABLE = Files.exists(Paths.get("agentprinting.conf")) static protected
Definition at line 50 of file IBaseTest.java.
Referenced by org.lightjason.agentspeak.beliefbase.TestCPropertyBeliefbase.belieflist(), org.lightjason.agentspeak.agent.TestCHanoiTowers.CGenerator.CGenerator(), and org.lightjason.agentspeak.agent.TestCHanoiTowers.execute().