LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.builtin.TestCActionRest Class Reference
org.lightjason.agentspeak.action.builtin.TestCActionRest Class Reference
REST-API test.
Public Member Functions
final void jsonlisterror ()
test json list error
final void jsonlistmultiple ()
test json list with multiple argument
final void jsonlistsingle ()
test json list with single argument
final void jsonobjecterror ()
test json object error
final void jsonobjectmultiple ()
test json object with multiple arguments
final void jsonobjectsingle ()
test json object with single argument
final void xmlobjecterror ()
test xml object error
final void xmlobjectmultiple ()
test xml object with single argument
final void xmlobjectsingle ()
test xml object with single argument
Static Public Member Functions
static void main (final String[] p_args)
test call
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.IBaseTest
final void invoketest ()
invoke all test manually
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 47 of file TestCActionRest.java.
Member Function Documentation
jsonlisterror()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.jsonlisterror ()
Definition at line 54 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.IBaseTest.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
jsonlistmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.jsonlistmultiple ()
Definition at line 94 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.rest.CJsonList.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.ILiteral.values().
jsonlistsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.jsonlistsingle ()
Definition at line 71 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.rest.CJsonList.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.ITerm.raw().
jsonobjecterror()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.jsonobjecterror ()
Definition at line 117 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.IBaseTest.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
jsonobjectmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.jsonobjectmultiple ()
Definition at line 157 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.rest.CJsonObject.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.ILiteral.values().
jsonobjectsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.jsonobjectsingle ()
Definition at line 135 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.rest.CJsonObject.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.functor().
main()
static void org.lightjason.agentspeak.action.builtin.TestCActionRest.main (final String [] p_args) static
Parameters
p_args command-line arguments
Definition at line 252 of file TestCActionRest.java.
References org.lightjason.agentspeak.IBaseTest.invoketest().
xmlobjecterror()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.xmlobjecterror ()
Definition at line 184 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.IBaseTest.execute(), and org.lightjason.agentspeak.language.CRawTerm< T >.from().
xmlobjectmultiple()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.xmlobjectmultiple ()
Definition at line 224 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.rest.CXMLObject.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), org.lightjason.agentspeak.language.ITerm.functor(), and org.lightjason.agentspeak.language.ILiteral.values().
xmlobjectsingle()
final void org.lightjason.agentspeak.action.builtin.TestCActionRest.xmlobjectsingle ()
Definition at line 202 of file TestCActionRest.java.
References org.lightjason.agentspeak.language.execution.IContext.EMPTYPLAN, org.lightjason.agentspeak.action.builtin.rest.CXMLObject.execute(), org.lightjason.agentspeak.language.CRawTerm< T >.from(), and org.lightjason.agentspeak.language.ITerm.functor().