LightJason - AgentSpeak(L++): org.lightjason.agentspeak.agent.TestCUnifier Class Reference
org.lightjason.agentspeak.agent.TestCUnifier Class Reference
test for unification
Public Member Functions
final void literalvaluesequentialtraversing () throws Exception
traversion of literal value content
final void literalvaluetraversing () throws Exception
traversion of literal value content
final void structurehash () throws Exception
literal value hashing
Static Public Member Functions
static void main (final String[] p_args) throws Exception
manuell running test
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.IBaseTest
final void invoketest ()
invoke all test manually
Static Protected Attributes inherited from org.lightjason.agentspeak.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("agentprinting.conf"))
enable printing of test-data
Detailed Description
Definition at line 48 of file TestCUnifier.java.
Member Function Documentation
literalvaluesequentialtraversing()
final void org.lightjason.agentspeak.agent.TestCUnifier.literalvaluesequentialtraversing () throws Exception
Exceptions
Exception parser exeception
Definition at line 81 of file TestCUnifier.java.
References org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.common.CPath.from(), org.lightjason.agentspeak.language.ILiteral.orderedvalues(), and org.lightjason.agentspeak.language.CLiteral.parse().
literalvaluetraversing()
final void org.lightjason.agentspeak.agent.TestCUnifier.literalvaluetraversing () throws Exception
Exceptions
Exception on parsing exception
Definition at line 57 of file TestCUnifier.java.
References org.lightjason.agentspeak.language.CLiteral.from(), org.lightjason.agentspeak.common.CPath.from(), org.lightjason.agentspeak.language.CLiteral.parse(), and org.lightjason.agentspeak.language.ILiteral.values().
main()
static void org.lightjason.agentspeak.agent.TestCUnifier.main (final String [] p_args) throws Exception static
Parameters
p_args arguments
Exceptions
Exception parser exception
Definition at line 139 of file TestCUnifier.java.
References org.lightjason.agentspeak.IBaseTest.invoketest().
structurehash()
final void org.lightjason.agentspeak.agent.TestCUnifier.structurehash () throws Exception
Exceptions
Exception parser exception
Definition at line 110 of file TestCUnifier.java.
References org.lightjason.agentspeak.language.CLiteral.parse(), and org.lightjason.agentspeak.language.IStructureHash.structurehash().